services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    volumes:
      - ./backend:/app/backend
      - ./phishing.db:/app/backend/phishing.db 
    ports:
      - "8000:8000"
